config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :blogs, :users, :categories
  root 'categories#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get    'login'   => 'session#new'
  post   'login'   => 'session#create'
  get 'logout' => 'session#destroy'
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

# :nodoc:
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]
  before_action :authenticate, except: %i[index show]
  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show; end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs or /blogs.json
  def create
    if is_writer?
      @blog = Blog.new(blog_params)

      respond_to do |format|
        if @blog.save
          format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
          format.json { render :show, status: :created, location: @blog }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
      end

    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @blog.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    current_member = User.find_by(id: session[:user_id])
    if is_writer? && current_member.user_id == blog.user_id || is_admin?
      respond_to do |format|
        if @blog.update(blog_params)
          format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
          format.json { render :show, status: :ok, location: @blog }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
      end

    else
      head 404
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  # Either admin can delete the blog or blogs's writer can do.
  def destroy
    current_member = User.find_by(id: session[:user_id])
    if is_writer? && current_member.user_id == blog.user_id || is_admin?
      @blog.destroy
      respond_to do |format|
        format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      head 404
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def is_writer?
    current_member = User.find_by(id: session[:user_id])
    current_member.role.userrole == 'writer'
  end

  def is_admin?
    current_member = User.find_by(id: session[:user_id])
    current_member.role.userrole == 'admin'
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :readtime, :category_id, :user_id, :content)
  end
end

app/helpers/blogs_helper.rb
# frozen_string_literal: true

# :nodoc:
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :readtime %>
    <%= form.number_field :readtime %>
  </div>

  <div class="field">
    <%= form.label :category_id, class: 'form-label' %>
    <%= form.select :category_id, options_for_select(Category.all.map{|r|[r.cname, r.id]}) , class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, :value => session[:user_id] %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Readtime</th>
      <th>Category</th>
      <th>User</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.readtime %></td>
        <td><%= blog.category_id %></td>
        <td><%= blog.user_id %></td>
        <td><%= blog.image %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= link_to 'New Blog', new_blog_path %><br><br>
  <%= link_to 'Categories Available', categories_path %><br><br>
</div>

<div>
<%= link_to 'Log In', login_path %><br><br>
<%= link_to 'Log  Out', logout_path %><br><br>
</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Readtime:</strong>
  <%= @blog.readtime %>
</p>

<p>
  <strong>Category:</strong>
  <%= @blog.category_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @blog.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>